import 'package:flutter_test/flutter_test.dart';
import 'package:querypod/core/database/drivers/alter_table_sql.dart';
import 'package:querypod/features/editor/domain/entities/table_data.dart';

void main() {
  const oldColumns = [
    TableColumnDefinition(
      name: 'id',
      originalName: 'id',
      type: 'INTEGER',
      isPrimaryKey: true,
      isNullable: false,
      isAutoIncrement: true,
    ),
    TableColumnDefinition(
      name: 'legacy',
      originalName: 'legacy',
      type: 'VARCHAR',
      length: 20,
    ),
  ];
  const newColumns = [
    TableColumnDefinition(
      name: 'id',
      originalName: 'id',
      type: 'INTEGER',
      isNullable: false,
    ),
    TableColumnDefinition(
      name: 'name',
      originalName: 'legacy',
      type: 'VARCHAR',
      length: 100,
      isPrimaryKey: true,
      isNullable: false,
    ),
  ];

  test('MySQL drops the old primary key before changing its columns', () {
    final statements = buildMySqlAlterStatements(
      oldTableName: 'items',
      newTableName: 'products',
      oldColumns: oldColumns,
      newColumns: newColumns,
    );

    expect(
      statements.first,
      startsWith('ALTER TABLE `items` DROP PRIMARY KEY'),
    );
    expect(
      statements.first,
      contains('CHANGE COLUMN `legacy` `name` VARCHAR(100) NOT NULL'),
    );
    expect(
      statements.first.indexOf('ADD PRIMARY KEY'),
      greaterThan(statements.first.indexOf('CHANGE COLUMN')),
    );
    expect(statements.last, 'RENAME TABLE `items` TO `products`');
  });

  test('PostgreSQL uses the real constraint and removes SERIAL safely', () {
    final statements = buildPostgresAlterStatements(
      oldTableName: 'items',
      newTableName: 'products',
      oldColumns: oldColumns,
      newColumns: newColumns,
      primaryKeyConstraint: 'custom_items_pk',
      serialSequences: const {'id': '"public"."custom_items_id_seq"'},
    );

    expect(
      statements.first,
      'ALTER TABLE "items" DROP CONSTRAINT "custom_items_pk"',
    );
    expect(
      statements,
      contains('ALTER TABLE "items" ALTER COLUMN "id" DROP DEFAULT'),
    );
    expect(
      statements,
      contains('DROP SEQUENCE IF EXISTS "public"."custom_items_id_seq"'),
    );
    expect(statements.last, 'ALTER TABLE "items" RENAME TO "products"');
  });

  test('PostgreSQL enables identity with BY DEFAULT semantics', () {
    const old = TableColumnDefinition(
      name: 'id',
      originalName: 'id',
      type: 'INTEGER',
      defaultValue: '7',
    );
    const updated = TableColumnDefinition(
      name: 'id',
      originalName: 'id',
      type: 'INTEGER',
      isAutoIncrement: true,
    );

    final statements = buildPostgresAlterStatements(
      oldTableName: 'items',
      newTableName: 'items',
      oldColumns: const [old],
      newColumns: const [updated],
      primaryKeyConstraint: null,
      serialSequences: const {},
    );

    expect(statements, [
      'ALTER TABLE "items" ALTER COLUMN "id" DROP DEFAULT',
      'ALTER TABLE "items" ALTER COLUMN "id" '
          'ADD GENERATED BY DEFAULT AS IDENTITY',
    ]);
  });

  test('changing composite primary-key order is a key change', () {
    const old = [
      TableColumnDefinition(
        name: 'first',
        originalName: 'first',
        type: 'INTEGER',
        isPrimaryKey: true,
      ),
      TableColumnDefinition(
        name: 'second',
        originalName: 'second',
        type: 'INTEGER',
        isPrimaryKey: true,
      ),
    ];
    const updated = [
      TableColumnDefinition(
        name: 'second',
        originalName: 'second',
        type: 'INTEGER',
        isPrimaryKey: true,
      ),
      TableColumnDefinition(
        name: 'first',
        originalName: 'first',
        type: 'INTEGER',
        isPrimaryKey: true,
      ),
    ];

    expect(primaryKeyChanged(old, updated), isTrue);
  });
}
