\connect querypod_lab

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(120) NOT NULL,
  profile_json jsonb NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL REFERENCES users(id),
  slug VARCHAR(120) NOT NULL UNIQUE,
  title VARCHAR(200) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  launched_on DATE NULL,
  metadata jsonb NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE project_members (
  project_id BIGINT NOT NULL REFERENCES projects(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  role_name VARCHAR(32) NOT NULL,
  joined_at TIMESTAMP NOT NULL,
  PRIMARY KEY (project_id, user_id)
);

CREATE TABLE activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id),
  actor_user_id BIGINT NULL REFERENCES users(id),
  action_name VARCHAR(64) NOT NULL,
  payload jsonb NULL,
  happened_at TIMESTAMP NOT NULL
);

INSERT INTO users (email, display_name, profile_json, timezone, created_at, updated_at) VALUES
  ('ada@example.com', 'Ada Lovelace', '{"theme":"solarized","editor":"vim"}', 'UTC', '2024-01-10 09:00:00', '2024-01-10 09:00:00'),
  ('grace@example.com', 'Grace Hopper', '{"theme":"light","editor":"emacs"}', 'America/New_York', '2024-01-11 10:30:00', '2024-01-11 10:30:00'),
  ('linus@example.com', 'Linus Torvalds', NULL, 'Europe/Helsinki', '2024-01-12 08:15:00', '2024-01-12 08:15:00');

INSERT INTO projects (owner_user_id, slug, title, status, launched_on, metadata, created_at, updated_at) VALUES
  (1, 'querypod-core', 'QueryPod Core', 'active', '2024-02-01', '{"language":"dart","dbs":["mysql","postgres"]}', '2024-02-01 09:00:00', '2024-02-01 09:00:00'),
  (2, 'driver-lab', 'Driver Lab', 'paused', NULL, '{"language":"sql","focus":"metadata"}', '2024-02-03 12:00:00', '2024-02-03 12:00:00');

INSERT INTO project_members (project_id, user_id, role_name, joined_at) VALUES
  (1, 1, 'owner', '2024-02-01 09:00:00'),
  (1, 2, 'editor', '2024-02-01 09:30:00'),
  (2, 2, 'owner', '2024-02-03 12:00:00'),
  (2, 3, 'reviewer', '2024-02-03 12:30:00');

INSERT INTO activity_logs (project_id, actor_user_id, action_name, payload, happened_at) VALUES
  (1, 1, 'project_created', '{"source":"seed"}', '2024-02-01 09:01:00'),
  (1, 2, 'member_joined', '{"role":"editor"}', '2024-02-01 09:31:00'),
  (2, NULL, 'status_synced', '{"state":"paused","reason":"fixture"}', '2024-02-03 12:35:00');
