\connect querypod_lab

CREATE TABLE "order" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group" VARCHAR(64) NOT NULL,
  notes TEXT NULL,
  inserted_at TIMESTAMP NOT NULL
);

CREATE TABLE json_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_key VARCHAR(64) NOT NULL UNIQUE,
  payload jsonb NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE temporal_edges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label_name VARCHAR(64) NOT NULL,
  due_date DATE NULL,
  happened_at TIMESTAMP NULL,
  created_ts TIMESTAMP NULL,
  updated_ts TIMESTAMP NULL
);

CREATE TABLE org_nodes (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NULL REFERENCES org_nodes(id),
  node_name VARCHAR(128) NOT NULL,
  depth_level INT NOT NULL DEFAULT 0
);

CREATE TABLE large_events (
  id BIGINT PRIMARY KEY,
  category_name VARCHAR(32) NOT NULL,
  event_name VARCHAR(128) NOT NULL,
  event_meta jsonb NOT NULL,
  created_at TIMESTAMP NOT NULL
);

INSERT INTO "order" ("group", notes, inserted_at) VALUES
  ('alpha', 'Reserved identifiers fixture', '2024-03-01 08:00:00'),
  ('beta', 'Second row', '2024-03-01 08:05:00');

INSERT INTO json_documents (doc_key, payload, created_at) VALUES
  ('settings', '{"enabled":true,"threshold":42,"tags":["db","ui"]}', '2024-03-04 10:00:00'),
  ('profile', '{"nested":{"level":2},"null_field":null}', '2024-03-05 11:00:00');

INSERT INTO temporal_edges (label_name, due_date, happened_at, created_ts, updated_ts) VALUES
  ('leap-day', '2024-02-29', '2024-02-29 23:59:59', '2024-02-29 23:59:59', '2024-03-01 00:00:00'),
  ('epoch-near', '1970-01-02', '1970-01-02 00:00:01', '1970-01-02 00:00:01', '1970-01-03 00:00:01'),
  ('future-nullable', '2099-12-31', NULL, NULL, NULL);

INSERT INTO org_nodes (id, parent_id, node_name, depth_level) VALUES
  (1, NULL, 'root', 0),
  (2, 1, 'engineering', 1),
  (3, 2, 'query-engine', 2),
  (4, 1, 'design', 1);

INSERT INTO large_events (id, category_name, event_name, event_meta, created_at)
SELECT
  g,
  CASE g % 4
    WHEN 0 THEN 'audit'
    WHEN 1 THEN 'sync'
    WHEN 2 THEN 'query'
    ELSE 'user'
  END,
  'event-' || LPAD(g::text, 4, '0'),
  jsonb_build_object('batch', (g - 1) / 100, 'important', g % 10 = 0, 'ordinal', g),
  TIMESTAMP '2024-04-01 00:00:00' + make_interval(mins => g)
FROM generate_series(1, 1000) AS g;
