#!/usr/bin/env bash

set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

target="${1:-all}"

sample_enabled "${target}" "sakila" && download_if_missing "${SAMPLE_SAKILA_URL}" "${DOWNLOAD_DIR}/sakila-db.tar.gz"
sample_enabled "${target}" "world" && download_if_missing "${SAMPLE_WORLD_URL}" "${DOWNLOAD_DIR}/world-db.tar.gz"
sample_enabled "${target}" "employees" && download_if_missing "${SAMPLE_EMPLOYEES_URL}" "${DOWNLOAD_DIR}/employees-master.tar.gz"
sample_enabled "${target}" "dvdrental" && download_if_missing "${SAMPLE_DVDRENTAL_URL}" "${DOWNLOAD_DIR}/dvdrental.zip"
